enum BusinessLegalStructure {
  SOLE_PROPRIETORSHIP = 'Sole Proprietorship',
  CORPORATION = 'Corporation',
  GENERAL_PARTNERSHIP = 'General Partnership',
  LIMITED_PARTNERSHIP = 'Limited Partnership',
  LIMITED_LIABILITY_PARTNERSHIP = 'Limited Liability Partnership',
  LIMITED_LIABILITY_COMPANY = 'Limited Liability Company (LLC)',
  C_CORPORATION = 'C Corporation',
  S_CORPORATION = 'S Corporation',
  NONPROFIT = 'Nonprofit Organization',
  COOPERATIVE = 'Cooperative',
  B_CORPORATION = 'B Corporation',
}

enum BusinessIndustry {
  AGRICULTURE_FORESTRY = 'Agriculture and Forestry',
  MINING_QUARRYING = 'Mining and Quarrying',
  UTILITIES = 'Utilities',
  CONSTRUCTION = 'Construction',
  MANUFACTURING = 'Manufacturing',
  WHOLESALE_TRADE = 'Wholesale Trade',
  RETAIL_TRADE = 'Retail Trade',
  TRANSPORTATION_WAREHOUSING = 'Transportation and Warehousing',
  INFORMATION = 'Information',
  FINANCE_INSURANCE = 'Finance and Insurance',
  REAL_ESTATE = 'Real Estate and Rental and Leasing',
  PROFESSIONAL_SERVICES = 'Professional, Scientific, and Technical Services',
  MANAGEMENT = 'Management of Companies and Enterprises',
  ADMINISTRATIVE_SUPPORT = 'Administrative and Support Services',
  WASTE_MANAGEMENT = 'Waste Management and Remediation Services',
  EDUCATIONAL_SERVICES = 'Educational Services',
  HEALTHCARE_SOCIAL = 'Health Care and Social Assistance',
  ARTS_ENTERTAINMENT = 'Arts, Entertainment, and Recreation',
  ACCOMMODATION_FOOD = 'Accommodation and Food Services',
  OTHER_SERVICES = 'Other Services (Except Public Administration)',
  PUBLIC_ADMINISTRATION = 'Public Administration',
}

enum USState {
  ALABAMA = 'Alabama',
  ALASKA = 'Alaska',
  ARIZONA = 'Arizona',
  ARKANSAS = 'Arkansas',
  CALIFORNIA = 'California',
  COLORADO = 'Colorado',
  CONNECTICUT = 'Connecticut',
  DELAWARE = 'Delaware',
  FLORIDA = 'Florida',
  GEORGIA = 'Georgia',
  HAWAII = 'Hawaii',
  IDAHO = 'Idaho',
  ILLINOIS = 'Illinois',
  INDIANA = 'Indiana',
  IOWA = 'Iowa',
  KANSAS = 'Kansas',
  KENTUCKY = 'Kentucky',
  LOUISIANA = 'Louisiana',
  MAINE = 'Maine',
  MARYLAND = 'Maryland',
  MASSACHUSETTS = 'Massachusetts',
  MICHIGAN = 'Michigan',
  MINNESOTA = 'Minnesota',
  MISSISSIPPI = 'Mississippi',
  MISSOURI = 'Missouri',
  MONTANA = 'Montana',
  NEBRASKA = 'Nebraska',
  NEVADA = 'Nevada',
  NEW_HAMPSHIRE = 'New Hampshire',
  NEW_JERSEY = 'New Jersey',
  NEW_MEXICO = 'New Mexico',
  NEW_YORK = 'New York',
  NORTH_CAROLINA = 'North Carolina',
  NORTH_DAKOTA = 'North Dakota',
  OHIO = 'Ohio',
  OKLAHOMA = 'Oklahoma',
  OREGON = 'Oregon',
  PENNSYLVANIA = 'Pennsylvania',
  RHODE_ISLAND = 'Rhode Island',
  SOUTH_CAROLINA = 'South Carolina',
  SOUTH_DAKOTA = 'South Dakota',
  TENNESSEE = 'Tennessee',
  TEXAS = 'Texas',
  UTAH = 'Utah',
  VERMONT = 'Vermont',
  VIRGINIA = 'Virginia',
  WASHINGTON = 'Washington',
  WEST_VIRGINIA = 'West Virginia',
  WISCONSIN = 'Wisconsin',
  WYOMING = 'Wyoming',
}

const StateMajorCities = {
  [USState.ALABAMA]: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa'],
  [USState.ALASKA]: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla', 'Sitka'],
  [USState.ARIZONA]: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale'],
  [USState.ARKANSAS]: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale', 'Jonesboro'],
  [USState.CALIFORNIA]: ['Los Angeles', 'San Francisco', 'San Diego', 'San Jose', 'Sacramento'],
  [USState.COLORADO]: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Boulder'],
  [USState.CONNECTICUT]: ['Bridgeport', 'New Haven', 'Hartford', 'Stamford', 'Waterbury'],
  [USState.DELAWARE]: ['Wilmington', 'Dover', 'Newark', 'Middletown', 'Smyrna'],
  [USState.FLORIDA]: ['Miami', 'Orlando', 'Jacksonville', 'Tampa', 'St. Petersburg'],
  [USState.GEORGIA]: ['Atlanta', 'Augusta', 'Columbus', 'Macon', 'Savannah'],
  [USState.HAWAII]: ['Honolulu', 'Pearl City', 'Hilo', 'Kailua', 'Waipahu'],
  [USState.IDAHO]: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'],
  [USState.ILLINOIS]: ['Chicago', 'Aurora', 'Rockford', 'Joliet', 'Springfield'],
  [USState.INDIANA]: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel'],
  [USState.IOWA]: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City', 'Iowa City'],
  [USState.KANSAS]: ['Wichita', 'Overland Park', 'Kansas City', 'Olathe', 'Topeka'],
  [USState.KENTUCKY]: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'],
  [USState.LOUISIANA]: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'],
  [USState.MAINE]: ['Portland', 'Lewiston', 'Bangor', 'South Portland', 'Auburn'],
  [USState.MARYLAND]: ['Baltimore', 'Columbia', 'Germantown', 'Silver Spring', 'Waldorf'],
  [USState.MASSACHUSETTS]: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell'],
  [USState.MICHIGAN]: ['Detroit', 'Grand Rapids', 'Warren', 'Sterling Heights', 'Ann Arbor'],
  [USState.MINNESOTA]: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington'],
  [USState.MISSISSIPPI]: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'],
  [USState.MISSOURI]: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'],
  [USState.MONTANA]: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Butte'],
  [USState.NEBRASKA]: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island', 'Kearney'],
  [USState.NEVADA]: ['Las Vegas', 'Reno', 'Henderson', 'North Las Vegas', 'Sparks'],
  [USState.NEW_HAMPSHIRE]: ['Manchester', 'Nashua', 'Concord', 'Dover', 'Rochester'],
  [USState.NEW_JERSEY]: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison'],
  [USState.NEW_MEXICO]: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe', 'Roswell'],
  [USState.NEW_YORK]: ['New York City', 'Buffalo', 'Rochester', 'Syracuse', 'Albany'],
  [USState.NORTH_CAROLINA]: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem'],
  [USState.NORTH_DAKOTA]: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot', 'West Fargo'],
  [USState.OHIO]: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron'],
  [USState.OKLAHOMA]: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'],
  [USState.OREGON]: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Hillsboro'],
  [USState.PENNSYLVANIA]: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie', 'Reading'],
  [USState.RHODE_ISLAND]: ['Providence', 'Warwick', 'Cranston', 'Pawtucket', 'East Providence'],
  [USState.SOUTH_CAROLINA]: [
    'Columbia',
    'Charleston',
    'North Charleston',
    'Mount Pleasant',
    'Rock Hill',
  ],
  [USState.SOUTH_DAKOTA]: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings', 'Watertown'],
  [USState.TENNESSEE]: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'],
  [USState.TEXAS]: ['Houston', 'Dallas', 'Austin', 'San Antonio', 'Fort Worth'],
  [USState.UTAH]: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan', 'Orem'],
  [USState.VERMONT]: ['Burlington', 'South Burlington', 'Rutland', 'Barre', 'Montpelier'],
  [USState.VIRGINIA]: ['Virginia Beach', 'Norfolk', 'Chesapeake', 'Richmond', 'Newport News'],
  [USState.WASHINGTON]: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue'],
  [USState.WEST_VIRGINIA]: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg', 'Wheeling'],
  [USState.WISCONSIN]: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine'],
  [USState.WYOMING]: ['Cheyenne', 'Casper', 'Laramie', 'Gillette', 'Rock Springs'],
} as const;

export { BusinessLegalStructure, BusinessIndustry, USState, StateMajorCities };
