import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';
import '@rainbow-me/rainbowkit/styles.css';
import RootProviders from '@/providers/root-providers';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import { config } from '@/utils/cookie';
import { cn } from '@/lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get('cookie'));

  return (
    <html lang="en">
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <RootProviders initialState={initialState}>{children}</RootProviders>
      </body>
    </html>
  );
}
